[Main]
run_type = trainFF
trajectory_file = train6283_nonGC.traj
# test_trajectory_file = test.traj
# scaler_type = STDScaler
scaler_type = NoScaler
energy_training = True
force_training  = True
test_log_interval = 100
epochs_max = 100000
# screen_rcut = 0.0
# screen_k = 1.0
ifelectronegativity = True
ifhardness = True
chg_grad = True
restart = True
es_frac = 1.0
en_frac = 1.0
fp_timer = exp

[Parallelization]
process_num = 64
batch_num_per_proc = 1
thread_num = 1
device_type = CPU

[Fingerprints]
fp_type = BP
fp_parameter_file = fpParas.dat 
fp_use_existing = True
fp_dir = fingerprints
fp_batch_num = 1
test_fp_dir = test_fingerprints
fp_test_use_existing = True

[MachineLearningModel]
model_type = neural_network
hidden_layers = 96 16
activation_function = tanh

[LossFunction]
loss_type = SE
energy_coefficient = 100.0
force_coefficient  = 1.0

[Optimizer]
optimizer_type = LBFGS
learning_rate = 0.2
#optimizer_type = LBFGSScipy
#optimizer_type = ADAM

[Debug]
init_model_parameters = False
nn_values = False

